experiment:
    name: "imagenet"
    project: "muse"
    output_dir: "imagenet"
    max_train_examples: 110000000
    max_eval_examples: 12800
    save_every: 500
    eval_every: 500
    log_every: 50


model:
    vq_model:
        pretrained: "openMUSE/maskgit-vqgan-imagenet-f16-256"

    transformer:
        vocab_size: 2025 # (1024 + 1000 + 1 -> Vq + Imagenet + <mask>)
        max_position_embeddings: 257 # (+1 for class id)
        hidden_size: 512
        num_hidden_layers: 8
        num_attention_heads: 8
        intermediate_size: 2048
        codebook_size: 1024
        num_classes: 1000
        initializer_range: 0.02
        layer_norm_eps: 1e-6
        use_bias: False
        hidden_dropout: 0.0
        attention_dropout: 0.0

    gradient_checkpointing: True


dataset:
    params:
        path: "imagenet-1k" # path to imagenet dataset
        streaming: True
        shuffle_buffer_size: 10000
        batch_size: ${training.batch_size}
        workers: 2
        resolution: 256
        image_column: "image"
        label_column: "label"
    preprocessing:
        resolution: 256
        center_crop: True
        random_flip: True


optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 4e-3
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8


lr_scheduler:
    scheduler: "constant"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 500


training:
    gradient_accumulation_steps: 1
    batch_size: 128
    mixed_precision: "bf16"
    use_ema: False
    seed: 42
    max_train_steps: None
    num_train_epochs: 1
    overfit_one_batch: False
